apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: internal-app-tgb
  namespace: mobileapp
spec:
  serviceRef:
    name: internal-app-svc
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:339712886638:targetgroup/aerowise-t1-alb-tg/d5164128518efd33
  targetType: ip
